config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :dairy_types

      resources :coffee_types

      resources :coffee_orders

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  ActiveAdmin.routes(self)
  root to: "users#index"
  resources :dairy_types
  resources :coffee_types
  resources :coffee_orders
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/api/v1/dairy_types_controller.rb
class Api::V1::DairyTypesController < Api::V1::GraphitiController
  def index
    dairy_types = DairyTypeResource.all(params)
    respond_with(dairy_types)
  end

  def show
    dairy_type = DairyTypeResource.find(params)
    respond_with(dairy_type)
  end

  def create
    dairy_type = DairyTypeResource.build(params)

    if dairy_type.save
      render jsonapi: dairy_type, status: :created
    else
      render jsonapi_errors: dairy_type
    end
  end

  def update
    dairy_type = DairyTypeResource.find(params)

    if dairy_type.update_attributes
      render jsonapi: dairy_type
    else
      render jsonapi_errors: dairy_type
    end
  end

  def destroy
    dairy_type = DairyTypeResource.find(params)

    if dairy_type.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: dairy_type
    end
  end
end

app/controllers/dairy_types_controller.rb
class DairyTypesController < ApplicationController
  before_action :set_dairy_type, only: %i[show edit update destroy]

  def index
    @q = DairyType.ransack(params[:q])
    @dairy_types = @q.result(distinct: true).includes(:coffee_orders).page(params[:page]).per(10)
  end

  def show
    @coffee_order = CoffeeOrder.new
  end

  def new
    @dairy_type = DairyType.new
  end

  def edit; end

  def create
    @dairy_type = DairyType.new(dairy_type_params)

    if @dairy_type.save
      redirect_to @dairy_type, notice: "Dairy type was successfully created."
    else
      render :new
    end
  end

  def update
    if @dairy_type.update(dairy_type_params)
      redirect_to @dairy_type, notice: "Dairy type was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @dairy_type.destroy
    redirect_to dairy_types_url,
                notice: "Dairy type was successfully destroyed."
  end

  private

  def set_dairy_type
    @dairy_type = DairyType.find(params[:id])
  end

  def dairy_type_params
    params.require(:dairy_type).permit(:dairy_type)
  end
end

app/views/dairy_types/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Dairy Type #<%= dairy_type.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Dairy type</dt>
      <dd><%= dairy_type.dairy_type %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back dairy_type, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_dairy_type_url(dairy_type), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to dairy_type, method: :delete, data: { confirm: "Do you really want to delete this dairy_type?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(dairy_type.updated_at) %> ago
  </div>
</div>

app/views/dairy_types/_dairy_type_coffee_orders.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Coffee Orders

    <a data-toggle="collapse" href="#dairy_type_coffee_orders_new_form">
      Add coffee order
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @dairy_type.coffee_orders.each do |coffee_order| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to coffee_order, coffee_order %>

        <%= link_to coffee_order, method: :delete, data: { confirm: "Do you really want to delete this coffee_order" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="dairy_type_coffee_orders_new_form">
        <%= render partial: "dairy_types/dairy_type_coffee_orders_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/dairy_types/_dairy_type_coffee_orders_new_form.html.erb
<%= form_with(model: @coffee_order, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :coffe_type_id %>

    <%= f.collection_select :coffe_type_id, CoffeeType.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <%= f.hidden_field :dairy_type_id, value: @dairy_type.id %>

  <div class="form-check">
    <%= f.check_box :iced, class: "form-check-input" %>
    <%= f.label :iced, class: "form-check-label" %>
  </div>

  <div class="form-group">
    <%= f.label :modifications_other %>
    <%= f.text_area :modifications_other, rows: "3", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :rating %>

    <%= f.text_field :rating, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :picture %>

    <%= f.file_field :picture, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :date %>

    <%= f.date_select :date, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :user_id %>

    <%= f.collection_select :user_id, User.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :cafe %>
    <%= f.text_area :cafe, rows: "3", class: "form-control" %>
  </div>

  <%= f.submit "Create coffee order", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/dairy_types/_dairy_types_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "dairy_types_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :dairy_type_cont, "Dairy type contains" %>
    <%= f.text_field :dairy_type_cont, :class => "form-control", :placeholder => "Dairy type contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>




  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/dairy_types" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#dairy_types_filters">
  Show filters
</a>

app/views/dairy_types/_form.html.erb
<% was_validated = dairy_type.errors.any? %>

<%= form_with(model: dairy_type, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% dairy_type_class = "form-control" %>
    <% dairy_type_was_invalid = dairy_type.errors.include?(:dairy_type) %>

    <% if was_validated %>
      <% if dairy_type_was_invalid %>
        <% dairy_type_class << " is-invalid" %>
      <% else %>
        <% dairy_type_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :dairy_type %>
    <%= f.text_field :dairy_type, class: dairy_type_class, placeholder: "Enter dairy type" %>
    <% if dairy_type_was_invalid %>
      <% dairy_type.errors.full_messages_for(:dairy_type).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/dairy_types/_list_item.html.erb
<%= link_to dairy_type, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= dairy_type %>
    <small class="text-muted">
      <%= time_ago_in_words(dairy_type.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/dairy_types/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Dairy Type #<%= @dairy_type.id %>
      </h2>

      <div class="card-body">
        <%= render "form", dairy_type: @dairy_type %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/dairy_types/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Dairy Types

      <%= link_to new_dairy_type_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "dairy_types/dairy_types_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Dairy Types

        <%= link_to new_dairy_type_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @dairy_types, partial: "list_item", as: :dairy_type %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @dairy_types, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/dairy_types/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Dairy Type
      </h2>

      <div class="card-body">
        <%= render "form", dairy_type: @dairy_type %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/dairy_types/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @dairy_type, partial: "card", as: :dairy_type %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "dairy_types/dairy_type_coffee_orders" %>
  </div>
</div>