config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :dairy_types

      resources :coffee_types

      resources :coffee_orders

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  ActiveAdmin.routes(self)
  root to: "users#index"
  resources :dairy_types
  resources :coffee_types
  resources :coffee_orders
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/coffee_order.rb
class CoffeeOrder < ApplicationRecord
  mount_base64_uploader :picture, PictureUploader

  # Direct associations

  belongs_to :dairy_type

  belongs_to :coffe_type,
             class_name: "CoffeeType"

  belongs_to :user

  # Indirect associations

  # Validations

  validates :rating, numericality: { less_than_or_equal_to: 5 }

  # Scopes

  def to_s
    coffe_type.to_s
  end
end

app/controllers/api/v1/coffee_orders_controller.rb
class Api::V1::CoffeeOrdersController < Api::V1::GraphitiController
  def index
    coffee_orders = CoffeeOrderResource.all(params)
    respond_with(coffee_orders)
  end

  def show
    coffee_order = CoffeeOrderResource.find(params)
    respond_with(coffee_order)
  end

  def create
    coffee_order = CoffeeOrderResource.build(params)

    if coffee_order.save
      render jsonapi: coffee_order, status: :created
    else
      render jsonapi_errors: coffee_order
    end
  end

  def update
    coffee_order = CoffeeOrderResource.find(params)

    if coffee_order.update_attributes
      render jsonapi: coffee_order
    else
      render jsonapi_errors: coffee_order
    end
  end

  def destroy
    coffee_order = CoffeeOrderResource.find(params)

    if coffee_order.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: coffee_order
    end
  end
end

app/controllers/coffee_orders_controller.rb
class CoffeeOrdersController < ApplicationController
  before_action :set_coffee_order, only: %i[show edit update destroy]

  def index
    @q = CoffeeOrder.ransack(params[:q])
    @coffee_orders = @q.result(distinct: true).includes(:user, :coffe_type,
                                                        :dairy_type).page(params[:page]).per(10)
  end

  def show; end

  def new
    @coffee_order = CoffeeOrder.new
  end

  def edit; end

  def create
    @coffee_order = CoffeeOrder.new(coffee_order_params)

    if @coffee_order.save
      message = "CoffeeOrder was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @coffee_order, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @coffee_order.update(coffee_order_params)
      redirect_to @coffee_order,
                  notice: "Coffee order was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @coffee_order.destroy
    message = "CoffeeOrder was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to coffee_orders_url, notice: message
    end
  end

  private

  def set_coffee_order
    @coffee_order = CoffeeOrder.find(params[:id])
  end

  def coffee_order_params
    params.require(:coffee_order).permit(:coffe_type_id, :dairy_type_id,
                                         :iced, :modifications_other, :rating, :picture, :date, :user_id, :cafe)
  end
end

app/views/coffee_orders/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Coffee Order #<%= coffee_order.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Coffe type</dt>
      <dd>
        <% if @coffee_order.coffe_type.present? %>
          <%= link_to coffee_order.coffe_type, coffee_order.coffe_type %>
        <% end %>
      </dd>

      <dt>Dairy type</dt>
      <dd>
        <% if @coffee_order.dairy_type.present? %>
          <%= link_to coffee_order.dairy_type, coffee_order.dairy_type %>
        <% end %>
      </dd>

      <dt>Iced</dt>
      <dd><%= coffee_order.iced %></dd>

      <dt>Modifications other</dt>
      <dd><%= coffee_order.modifications_other %></dd>

      <dt>Rating</dt>
      <dd><%= coffee_order.rating %></dd>

      <dt>Picture</dt>
      <dd>
        <%= cl_image_tag @coffee_order.picture, class: "img-fluid" %>
      </dd>

      <dt>Date</dt>
      <dd><%= coffee_order.date %></dd>

      <dt>User</dt>
      <dd>
        <% if @coffee_order.user.present? %>
          <%= link_to coffee_order.user, coffee_order.user %>
        <% end %>
      </dd>

      <dt>Cafe</dt>
      <dd><%= coffee_order.cafe %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back coffee_order, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_coffee_order_url(coffee_order), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to coffee_order, method: :delete, data: { confirm: "Do you really want to delete this coffee_order?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(coffee_order.updated_at) %> ago
  </div>
</div>

app/views/coffee_orders/_coffee_orders_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "coffee_orders_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :cafe_cont, "Cafe contains" %>
    <%= f.text_field :cafe_cont, :class => "form-control", :placeholder => "Cafe contains" %>
  </div>

  <div class="form-group">
    <%= f.label :date, "Date" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='dategteqPicker' data-target-input="nearest">
          <%= f.text_field :date_gteq, :class => "form-control datetimepicker-input", :placeholder => "Date greater than or equal to", :data => {:target => '#dategteqPicker'} %>
          <div class="input-group-append" data-target='#dategteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='datelteqPicker' data-target-input="nearest">
          <%= f.text_field :date_lteq, :class => "form-control datetimepicker-input", :placeholder => "Date less than or equal to", :data => {:target => '#datelteqPicker'} %>
          <div class="input-group-append" data-target='#datelteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#dategteqPicker').datetimepicker({
              format: 'MM/DD/YYYY'
          });
          $('#datelteqPicker').datetimepicker({
              useCurrent: false,
              format: 'MM/DD/YYYY'
          });
          $('#dategteqPicker').on("dp.change", function (e) {
              $('#datelteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#datelteqPicker').on("dp.change", function (e) {
              $('#dategteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>

  <div class="form-group">
    <%= f.label :rating, "Rating" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <%= f.text_field :rating_gteq, :class => "form-control", :placeholder => "Rating greater than or equal to" %>
      </div>
      <div class='col-md-6'>
        <%= f.text_field :rating_lteq, :class => "form-control", :placeholder => "Rating less than or equal to" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :modifications_other_cont, "Modifications other contains" %>
    <%= f.text_field :modifications_other_cont, :class => "form-control", :placeholder => "Modifications other contains" %>
  </div>

  <div class="form-group">
    <%= f.label :iced_eq, "Iced" %>
    <div>
      <label class="radio-inline">
        <%= f.radio_button :iced_eq, "1", checked: ((params[:q] && params[:q][:iced_eq]) == "1" ? "checked" : "") %> Yes
      </label>
      <label class="radio-inline">
        <%= f.radio_button :iced_eq, "0", checked: ((params[:q] && params[:q][:iced_eq]) == "0" ? "checked" : "")%> No
      </label>
      <label class="radio-inline">
        <%= f.radio_button :iced_eq, ""%> Either
      </label>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :user_name_cont, "User name contains" %>
    <%= f.text_field :user_name_cont, :class => "form-control", :placeholder => "User name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :coffe_type_coffee_type_cont, "Coffe type coffee_type contains" %>
    <%= f.text_field :coffe_type_coffee_type_cont, :class => "form-control", :placeholder => "Coffe type coffee_type contains" %>
  </div>

  <div class="form-group">
    <%= f.label :dairy_type_dairy_type_cont, "Dairy type dairy_type contains" %>
    <%= f.text_field :dairy_type_dairy_type_cont, :class => "form-control", :placeholder => "Dairy type dairy_type contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/coffee_orders" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#coffee_orders_filters">
  Show filters
</a>

app/views/coffee_orders/_form.html.erb
<% was_validated = coffee_order.errors.any? %>

<%= form_with(model: coffee_order, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% coffe_type_class = "form-control" %>
    <% coffe_type_was_invalid = coffee_order.errors.include?(:coffe_type) %>

    <% if was_validated %>
      <% if coffe_type_was_invalid %>
        <% coffe_type_class << " is-invalid" %>
      <% else %>
        <% coffe_type_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :coffe_type_id %>
    <%= f.collection_select :coffe_type_id, CoffeeType.all, :id, :to_s, {}, class: "form-control" %>
    <% if coffe_type_was_invalid %>
      <% coffee_order.errors.full_messages_for(:coffe_type).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% dairy_type_class = "form-control" %>
    <% dairy_type_was_invalid = coffee_order.errors.include?(:dairy_type) %>

    <% if was_validated %>
      <% if dairy_type_was_invalid %>
        <% dairy_type_class << " is-invalid" %>
      <% else %>
        <% dairy_type_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :dairy_type_id %>
    <%= f.collection_select :dairy_type_id, DairyType.all, :id, :to_s, {}, class: "form-control" %>
    <% if dairy_type_was_invalid %>
      <% coffee_order.errors.full_messages_for(:dairy_type).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-check">
    <% iced_class = "form-check-input" %>
    <% iced_was_invalid = coffee_order.errors.include?(:iced) %>

    <% if was_validated %>
      <% if iced_was_invalid %>
        <% iced_class << " is-invalid" %>
      <% else %>
        <% iced_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :iced, class: "form-check-label" do %>
      <%= f.check_box :iced, class: iced_class %> Iced
    <% end %>
    <% if iced_was_invalid %>
      <% coffee_order.errors.full_messages_for(:iced).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% modifications_other_class = "form-control" %>
    <% modifications_other_was_invalid = coffee_order.errors.include?(:modifications_other) %>

    <% if was_validated %>
      <% if modifications_other_was_invalid %>
        <% modifications_other_class << " is-invalid" %>
      <% else %>
        <% modifications_other_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :modifications_other %>
    <%= f.text_area :modifications_other, class: modifications_other_class, placeholder: "Enter modifications other" %>
    <% if modifications_other_was_invalid %>
      <% coffee_order.errors.full_messages_for(:modifications_other).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% rating_class = "form-control" %>
    <% rating_was_invalid = coffee_order.errors.include?(:rating) %>

    <% if was_validated %>
      <% if rating_was_invalid %>
        <% rating_class << " is-invalid" %>
      <% else %>
        <% rating_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :rating %>
    <%= f.number_field :rating, class: rating_class, placeholder: "Enter rating" %>
    <% if rating_was_invalid %>
      <% coffee_order.errors.full_messages_for(:rating).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% picture_class = "form-control" %>
    <% picture_was_invalid = coffee_order.errors.include?(:picture) %>

    <% if was_validated %>
      <% if picture_was_invalid %>
        <% picture_class << " is-invalid" %>
      <% else %>
        <% picture_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :picture %>
    <%= f.file_field :picture, class: "form-control" %>
    <% if picture_was_invalid %>
      <% coffee_order.errors.full_messages_for(:picture).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% date_class = "form-control" %>
    <% date_was_invalid = coffee_order.errors.include?(:date) %>

    <% if was_validated %>
      <% if date_was_invalid %>
        <% date_class << " is-invalid" %>
      <% else %>
        <% date_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :date %>
    <%= f.date_select :date, class: date_class, placeholder: "Enter date" %>
    <% if date_was_invalid %>
      <% coffee_order.errors.full_messages_for(:date).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% user_class = "form-control" %>
    <% user_was_invalid = coffee_order.errors.include?(:user) %>

    <% if was_validated %>
      <% if user_was_invalid %>
        <% user_class << " is-invalid" %>
      <% else %>
        <% user_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :user_id %>
    <%= f.collection_select :user_id, User.all, :id, :to_s, {}, class: "form-control" %>
    <% if user_was_invalid %>
      <% coffee_order.errors.full_messages_for(:user).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% cafe_class = "form-control" %>
    <% cafe_was_invalid = coffee_order.errors.include?(:cafe) %>

    <% if was_validated %>
      <% if cafe_was_invalid %>
        <% cafe_class << " is-invalid" %>
      <% else %>
        <% cafe_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :cafe %>
    <%= f.text_area :cafe, class: cafe_class, placeholder: "Enter cafe" %>
    <% if cafe_was_invalid %>
      <% coffee_order.errors.full_messages_for(:cafe).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/coffee_orders/_list_item.html.erb
<%= link_to coffee_order, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= coffee_order %>
    <small class="text-muted">
      <%= time_ago_in_words(coffee_order.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/coffee_orders/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Coffee Order #<%= @coffee_order.id %>
      </h2>

      <div class="card-body">
        <%= render "form", coffee_order: @coffee_order %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/coffee_orders/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Coffee Orders

      <%= link_to new_coffee_order_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "coffee_orders/coffee_orders_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Coffee Orders

        <%= link_to new_coffee_order_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @coffee_orders, partial: "list_item", as: :coffee_order %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @coffee_orders, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/coffee_orders/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Coffee Order
      </h2>

      <div class="card-body">
        <%= render "form", coffee_order: @coffee_order %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/coffee_orders/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @coffee_order, partial: "card", as: :coffee_order %>
  </div>
</div>