config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :dairy_types

      resources :coffee_types

      resources :coffee_orders

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  ActiveAdmin.routes(self)
  root to: "users#index"
  resources :dairy_types
  resources :coffee_types
  resources :coffee_orders
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Direct associations

  has_many   :coffee_orders,
             dependent: :destroy

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    name
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::GraphitiController
  def index
    users = UserResource.all(params)
    respond_with(users)
  end

  def show
    user = UserResource.find(params)
    respond_with(user)
  end

  def create
    user = UserResource.build(params)

    if user.save
      render jsonapi: user, status: :created
    else
      render jsonapi_errors: user
    end
  end

  def update
    user = UserResource.find(params)

    if user.update_attributes
      render jsonapi: user
    else
      render jsonapi_errors: user
    end
  end

  def destroy
    user = UserResource.find(params)

    if user.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: user
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true).includes(:coffee_orders).page(params[:page]).per(10)
  end

  def show
    @coffee_order = CoffeeOrder.new
  end

  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: "User was successfully created."
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "User was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: "User was successfully destroyed."
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :coffee_preference)
  end
end

app/views/users/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    User #<%= user.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Name</dt>
      <dd><%= user.name %></dd>

      <dt>Email</dt>
      <dd><%= user.email %></dd>

      <dt>Password</dt>
      <dd><%= user.password %></dd>

      <dt>Coffee preference</dt>
      <dd><%= user.coffee_preference %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back user, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_user_url(user), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to user, method: :delete, data: { confirm: "Do you really want to delete this user?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(user.updated_at) %> ago
  </div>
</div>

app/views/users/_form.html.erb
<% was_validated = user.errors.any? %>

<%= form_with(model: user, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% name_class = "form-control" %>
    <% name_was_invalid = user.errors.include?(:name) %>

    <% if was_validated %>
      <% if name_was_invalid %>
        <% name_class << " is-invalid" %>
      <% else %>
        <% name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :name %>
    <%= f.text_field :name, class: name_class, placeholder: "Enter name" %>
    <% if name_was_invalid %>
      <% user.errors.full_messages_for(:name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% email_class = "form-control" %>
    <% email_was_invalid = user.errors.include?(:email) %>

    <% if was_validated %>
      <% if email_was_invalid %>
        <% email_class << " is-invalid" %>
      <% else %>
        <% email_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :email %>
    <%= f.text_field :email, class: email_class, placeholder: "Enter email" %>
    <% if email_was_invalid %>
      <% user.errors.full_messages_for(:email).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% password_class = "form-control" %>
    <% password_was_invalid = user.errors.include?(:password) %>

    <% if was_validated %>
      <% if password_was_invalid %>
        <% password_class << " is-invalid" %>
      <% else %>
        <% password_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :password %>
    <%= f.text_field :password, class: password_class, placeholder: "Enter password" %>
    <% if password_was_invalid %>
      <% user.errors.full_messages_for(:password).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% coffee_preference_class = "form-control" %>
    <% coffee_preference_was_invalid = user.errors.include?(:coffee_preference) %>

    <% if was_validated %>
      <% if coffee_preference_was_invalid %>
        <% coffee_preference_class << " is-invalid" %>
      <% else %>
        <% coffee_preference_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :coffee_preference %>
    <%= f.text_area :coffee_preference, class: coffee_preference_class, placeholder: "Enter coffee preference" %>
    <% if coffee_preference_was_invalid %>
      <% user.errors.full_messages_for(:coffee_preference).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/users/_list_item.html.erb
<%= link_to user, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= user %>
    <small class="text-muted">
      <%= time_ago_in_words(user.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/users/_user_coffee_orders.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Coffee Orders

    <a data-toggle="collapse" href="#user_coffee_orders_new_form">
      Add coffee order
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @user.coffee_orders.each do |coffee_order| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to coffee_order, coffee_order %>

        <%= link_to coffee_order, method: :delete, data: { confirm: "Do you really want to delete this coffee_order" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="user_coffee_orders_new_form">
        <%= render partial: "users/user_coffee_orders_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/users/_user_coffee_orders_new_form.html.erb
<%= form_with(model: @coffee_order, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :coffe_type_id %>

    <%= f.collection_select :coffe_type_id, CoffeeType.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :dairy_type_id %>

    <%= f.collection_select :dairy_type_id, DairyType.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <div class="form-check">
    <%= f.check_box :iced, class: "form-check-input" %>
    <%= f.label :iced, class: "form-check-label" %>
  </div>

  <div class="form-group">
    <%= f.label :modifications_other %>
    <%= f.text_area :modifications_other, rows: "3", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :rating %>

    <%= f.text_field :rating, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :picture %>

    <%= f.file_field :picture, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :date %>

    <%= f.date_select :date, class: "form-control" %>
  </div>

  <%= f.hidden_field :user_id, value: @user.id %>

  <div class="form-group">
    <%= f.label :cafe %>
    <%= f.text_area :cafe, rows: "3", class: "form-control" %>
  </div>

  <%= f.submit "Create coffee order", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/users/_users_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "users_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :name_cont, "Name contains" %>
    <%= f.text_field :name_cont, :class => "form-control", :placeholder => "Name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :coffee_preference_cont, "Coffee preference contains" %>
    <%= f.text_field :coffee_preference_cont, :class => "form-control", :placeholder => "Coffee preference contains" %>
  </div>

  <div class="form-group">
    <%= f.label :email_cont, "Email contains" %>
    <%= f.text_field :email_cont, :class => "form-control", :placeholder => "Email contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>




  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/users" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#users_filters">
  Show filters
</a>

app/views/users/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit User #<%= @user.id %>
      </h2>

      <div class="card-body">
        <%= render "form", user: @user %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Users

      <%= link_to new_user_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "users/users_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Users

        <%= link_to new_user_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @users, partial: "list_item", as: :user %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @users, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New User
      </h2>

      <div class="card-body">
        <%= render "form", user: @user %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @user, partial: "card", as: :user %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "users/user_coffee_orders" %>
  </div>
</div>